#!/bin/bash
# process all joint.event.root files for given year and cluster with reco-cascade program
# arguments: year(16,17,18,19), cluster(from zero/0), optional parameter nCores used for processing

[ -z $1 ] && echo "Season info missing" && exit
[ -z $2 ] && echo "Cluster info missing" && exit

# parallel "(time ./new-reconstruct-cascade -s 20$1 -c $2 -r {1} -q -g) 2>&1 | tee ../logs/programOutput_$1_$2_{1}.log" ::: {1..999}
parallel "(time reco-cascade --season 20$1 -c $2 -r {1} --config /home/fajtak/bars/build/resources/reco-cascade_promptReco.rc -t dev-1.0 -o /mnt/cephfs/users/fajtak/cluster$2/) 2>&1 | tee /mnt/cephfs/users/fajtak/cluster$2/logs/programOutput_$1_$2_{1}.log" ::: {1..999}
